---
version: '3.8'

services:
  traefik:
    image: traefik:{{ cookiecutter.__devops_traefik_version }}

    ports:
      - 80:80
      - 443:443

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network={{ cookiecutter.__devops_swarm_public_network }}
        - traefik.constraint-label=public
{%- if cookiecutter.__devops_traefik_stack_include_ui == 'yes' %}
        - traefik.http.services.traefik-public.loadbalancer.server.port=8000
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$uZPT5Fgu$$AmlIdamxT5ipBvPlsdfD70
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik-{{ cookiecutter.hostname }}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
{%- else %}
        #- traefik.http.services.traefik-public.loadbalancer.server.port=8000
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        #- traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$uZPT5Fgu$$AmlIdamxT5ipBvPlsdfD70
        #- traefik.http.routers.traefik-public-https.rule=Host(`traefik-{{ cookiecutter.hostname }}`)
        #- traefik.http.routers.traefik-public-https.entrypoints=https
        #- traefik.http.routers.traefik-public-https.tls=true
        #- traefik.http.routers.traefik-public-https.service=api@internal
        #- traefik.http.routers.traefik-public-https.middlewares=admin-auth
{%- endif %}

        # GENERIC MIDDLEWARES
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.gzip.compress=true
        - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

        # GENERIC ROUTERS
        - traefik.http.routers.generic-https-redirect.entrypoints=http
        - traefik.http.routers.generic-https-redirect.rule=HostRegexp(`{host:.*}`)
        - traefik.http.routers.generic-https-redirect.priority=1
        - traefik.http.routers.generic-https-redirect.middlewares=https-redirect

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vol-traefik-certs:/certificates

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email={{ cookiecutter.email }}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --log.level=INFO
      - --api

    networks:
      - {{ cookiecutter.__devops_swarm_public_network }}

{%- if cookiecutter.devops_cache == '1' %}
  purger:
    image: ghcr.io/kitconcept/cluster-purger:latest
    environment:
      PURGER_SERVICE_NAME: varnish
      PURGER_SERVICE_PORT: 80
      PURGER_PUBLIC_SITES: "['{{ cookiecutter.hostname }}']"
    networks:
      - {{ cookiecutter.__devops_swarm_public_network }}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  varnish:
    image: {{ cookiecutter.__container_image_prefix }}-varnish:${STACK_PARAM:-latest}
    command:
      - '-p'
      - 'nuke_limit=2000'
      - '-p'
      - 'workspace_client=192k'
      - '-p'
      - 'workspace_backend=192k'
    depends_on:
      - frontend
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.constraint-label=public
        # SERVICE
        - traefik.http.services.svc-varnish.loadbalancer.server.port=80
        # ROUTERS
        ## Router: Varnish Public
        - traefik.http.routers.rt-varnish-public.rule=Host(`{{ cookiecutter.hostname }}`)
        - traefik.http.routers.rt-varnish-public.entrypoints=https
        - traefik.http.routers.rt-varnish-public.tls=true
        - traefik.http.routers.rt-varnish-public.tls.certresolver=le
        - traefik.http.routers.rt-varnish-public.service=svc-varnish
        - traefik.http.routers.rt-varnish-public.middlewares=gzip
{%- endif %}

  frontend:
    image: {{ cookiecutter.__container_image_prefix }}-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    networks:
      - {{ cookiecutter.__devops_swarm_public_network }}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network={{ cookiecutter.__devops_swarm_public_network }}
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.svc-frontend.loadbalancer.server.port=3000
        # Routers
{%- if cookiecutter.devops_cache == '0' %}
        ## /
        - traefik.http.routers.rt-frontend.rule=Host(`{{ cookiecutter.hostname }}`)
        - traefik.http.routers.rt-frontend.entrypoints=https
        - traefik.http.routers.rt-frontend.tls=true
        - traefik.http.routers.rt-frontend.tls.certresolver=le
        - traefik.http.routers.rt-frontend.service=svc-frontend
        - traefik.http.routers.rt-frontend.middlewares=gzip
{%- else %}
        ## / (Internal)
        - traefik.http.routers.rt-frontend.rule=Host(`{{ cookiecutter.hostname }}`) && Headers(`X-Varnish-Routed`, `1`)
        - traefik.http.routers.rt-frontend.entrypoints=http
        - traefik.http.routers.rt-frontend.service=svc-frontend
{%- endif %}

  backend:
    image: {{ cookiecutter.__container_image_prefix }}-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-{{ cookiecutter.__devops_db_password }}}' port='${DB_PORT:-5432}'"
    depends_on:
      - db
    networks:
      - {{ cookiecutter.__devops_swarm_public_network }}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network={{ cookiecutter.__devops_swarm_public_network }}
        - traefik.constraint-label=public
        # Services
        - traefik.http.services.svc-backend.loadbalancer.server.port=8080

        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/{{ cookiecutter.hostname }}/Plone/++api++/VirtualHostRoot$$1"

        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.mw-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.mw-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/{{ cookiecutter.hostname }}/Plone/VirtualHostRoot/_vh_ClassicUI$$1"

        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.mw-backend-auth.basicauth.users=admin:$$apr1$$uZPT5Fgu$$AmlIdamxT5ipBvPlsdfD70

        # Routes
{%- if cookiecutter.devops_cache == '0' %}
        ## /++api++
        - traefik.http.routers.rt-backend-api.rule=Host(`{{ cookiecutter.hostname }}`) && PathPrefix(`/++api++`)
        - traefik.http.routers.rt-backend-api.entrypoints=https
        - traefik.http.routers.rt-backend-api.tls=true
        - traefik.http.routers.rt-backend-api.service=svc-backend
        - traefik.http.routers.rt-backend-api.middlewares=gzip,mw-backend-vhm-api
{%- else %}
        ## /++api++ (Internal)
        - traefik.http.routers.rt-backend-api.rule=Host(`{{ cookiecutter.hostname }}`) && PathPrefix(`/++api++`) && Headers(`X-Varnish-Routed`, `1`)
        - traefik.http.routers.rt-backend-api.entrypoints=http
        - traefik.http.routers.rt-backend-api.service=svc-backend
        - traefik.http.routers.rt-backend-api.middlewares=mw-backend-vhm-api
{%- endif %}
        ## /ClassicUI
        - traefik.http.routers.rt-backend-classic.rule=Host(`{{ cookiecutter.hostname }}`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.rt-backend-classic.entrypoints=https
        - traefik.http.routers.rt-backend-classic.tls=true
        - traefik.http.routers.rt-backend-classic.service=svc-backend
        - traefik.http.routers.rt-backend-classic.middlewares=gzip,mw-backend-auth,mw-backend-vhm-classic

  db:
    image: postgres:{{ cookiecutter.__devops_db_version }}
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: {{ cookiecutter.__devops_db_password }}
      POSTGRES_DB: plone
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        order: stop-first
    volumes:
      - vol-site-data:/var/lib/postgresql/data
    networks:
      - {{ cookiecutter.__devops_swarm_public_network }}

volumes:
  vol-traefik-certs: {}
  vol-site-data:
    driver_opts:
      type: none
      device: /srv/{{ cookiecutter.project_slug }}/data
      o: bind

networks:
  {{ cookiecutter.__devops_swarm_public_network }}:
    internal: true
    driver: overlay
