---
collections:
  - name: community.general
    version: "5.2.0"

  - name: community.docker
    version: "2.6.0"

roles:
  - src: https://github.com/tangrama/tangrama.common.git
    name: tangrama.common
    version: main

  - src: https://github.com/tangrama/tangrama.ufw.git
    name: tangrama.ufw
    version: main

  - src: https://github.com/tangrama/tangrama.motd.git
    name: tangrama.motd
    version: main

  - src: https://github.com/tangrama/tangrama.users.git
    name: tangrama.users
    version: main

  - name: geerlingguy.swap
    version: 1.0.2
